### ISSUE TITLE
More dynamic behaviour !

### ISSUE THREAD

**Issue by Diaskhan** [yvettemuki/typeflow-editor#2]
Maybe its to possible to store left panel elements to json file ?

And provide feature and behaviour for each element in separate js logic file ? 

Main problem of draw.io is very huge code base.

All developers need two simple things.
It easy to extend left panel elements. For example store all elements in json file !

In this element describe some possible logic to render in right panel! 
An example https://www.creatio.com/sites/default/files/bpmonline/styles/drag_mobile/public/features/popup/1_1_dizayner_processov_big.png?itok=qzwCP6Oi

**Comment by Diaskhan** [comment]
Each element has own render logic in right panel !

**Comment by Diaskhan** [comment]
Good job by the way !

**Comment by yvettemuki** [comment]
Wow, thanks for the nice idea, actually I am working on store the element setting storage! And thanks for your helpful suggestion.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Diaskhan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 凌晨4:00
收件人:&nbsp;"yvettemuki/typeflow-editor"<typeflow-editor@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yvettemuki/typeflow-editor] More dynamic behaviour ! (#2)




Maybe its to possible to store left panel elements to json file ?
 
And provide feature and behaviour for each element in separate js logic file ?
 
Main problem of draw.io is very huge code base.
 
All developers need two simple things.
 It easy to extend left panel elements. For example store all elements in json file !
 
In this element describe some possible logic to render in right panel!
 An example https://www.creatio.com/sites/default/files/bpmonline/styles/drag_mobile/public/features/popup/1_1_dizayner_processov_big.png?itok=qzwCP6Oi

**Comment by Diaskhan** [comment]
I m to could help. I know litle bit vuejs and mxgraph! And provide russian translations if needed !

Actually i am still developing bpmn engine and i have a vision that mxgraph is best for workflow editor !

**Comment by yvettemuki** [comment]
This is the open source project, welcome different thinking and idea! You can join to help! And also we can exchange idea on mxgraph!

I have add the local storage for the setting on the left panel, but I will not add the cloud storage until connecting to the back-end.
