### ISSUE TITLE
npm run serve with error

### ISSUE THREAD

**Issue by Diaskhan** [yvettemuki/typeflow-editor#3]
I entered 
npm install

After entering
Npm run serve

throws an error
![image](https://user-images.githubusercontent.com/15046677/72548231-7964ab80-38b8-11ea-920d-cd7fd4a77ca6.png)

**Comment by Diaskhan** [comment]
c:\JS_Projects\typeflow-editor-master>node --version
v7.9.0

**Comment by Diaskhan** [comment]
[npm-debug.log](https://github.com/yvettemuki/typeflow-editor/files/4072775/npm-debug.log)

**Comment by yvettemuki** [comment]
maybe it's your node version problem, try to read this page:
https://cli.vuejs.org/guide/installation.html
"Vue CLI requires Node.js version 8.9 or above (8.11.0+ recommended)."

By the way, thanks for the issue, I will update the readme

**Comment by Diaskhan** [comment]
Updated to lastest Thanks!
That helped!
