### ISSUE TITLE
Where Left panel stores elements ?

### ISSUE THREAD

**Issue by Diaskhan** [yvettemuki/typeflow-editor#4]
I've added 1 eleement.

Where Did U store left Panel Elements ?
![image](https://user-images.githubusercontent.com/15046677/72601283-4c0f1080-393f-11ea-9c00-8e52421949be.png)

**Comment by yvettemuki** [comment]
Right now just use the local storage, in the future will connect to the database

**Comment by Diaskhan** [comment]
I guesse best option is store in file at backend ! And backend file will generate json file on server side !

**Comment by Diaskhan** [comment]
To make front and backend independence!

**Comment by yvettemuki** [comment]
yes, the system will assure both two ends data  persistence which are local storage way and back end database( or use file is also a convenient way). I will try later.
