### ISSUE TITLE
What about Mxgraph Vuejs

### ISSUE THREAD

**Issue by Diaskhan** [yvettemuki/typeflow-editor#6]
What About Creating Library over Mxgraph that could connect vuejs world and mxgraph ?

Create or provide some abstract Api over mxgrpah?
Many user want to use mxgraph with vuejs, but there poor conectiviti!

**Comment by Diaskhan** [comment]
I got some Ideas how it Goona be look like !

**Comment by yvettemuki** [comment]
wow! That's really good idea! But I don't have the experience about create library like that, I do need help.

**Comment by Diaskhan** [comment]
I've looked pointsjs,diagram js,mxgraph.
There for digraming library need only one few things.
1.Extensible Editor (load elements from some repository)
Creating Businnes objects that could bind some data,mxgraph allow it!
https://jgraph.github.io/mxgraph/javascript/examples/userobject.html

2.Image for elements, could use 
https://fontawesome.com/

3.Possible data mappings to basic types.String,integer,Guid,float, and some other data types!
Similar to this. Need for WorkFlow !
![image](https://user-images.githubusercontent.com/15046677/72681119-ae584480-3aea-11ea-953f-8f2318d6c02a.png)


Z.Just view diagrams.

**Comment by Diaskhan** [comment]
For Z, there could provide some api to do Overlay Images for elements !
https://camo.githubusercontent.com/7a601662722bbb71748aac5da6f4cd451096a40d/687474703a2f2f62706d6e2e696f2f6173736574732f696d672f656d6265642e706e67

Element has a number 1,2,3

**Comment by Diaskhan** [comment]
Thanks i have finded interesting solution
Here 
https://github.com/lanniu/vue-mxgraph-example/blob/master/doc/customToolbar_design_en_us.md

**Comment by yvettemuki** [comment]
good, it's actually a good solution!
In my project, I just choose the data of the element and element background color as the dynamic  one, but limit the size and the style of each element
